version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6  
  node: circleci/node@5.0.2
  
jobs:
  install-node:
    docker:
      - image: 'cimg/node@16.13.2'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version

  workflows:
    test_my_app:
      jobs:
        - ins
        - node/test:
            test-results-for: jest
            requires: test_my_app

