version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6  
  node: circleci/node@5.0.2
  
jobs:
  install-node-example:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version

  workflows:
    test_my_app:
      jobs:
        - install-node-example
    test:
      jobs:
        - node/test:
            test-results-for: jest
      re        

