on: ["push", "pull_request"]

name: Test Coveralls
working-directory: /home/circleci/project/musician

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    working-directory: musician
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 
    - uses: actions/setup-node@v1
    - with:
        node-version: 10.x

    - name: npm install, make test-coverage
    - run: |
        npm install
        make test-coverage

    - name: Coveralls
    - uses: coverallsapp/github-action@master
    - with:
        github-token: ${{ secrets.GITHUB_TOKEN }}