version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    docker:
      - image: 'circleci/node:16.13.2'
    steps:
      - checkout
      - run:
          name: Install and Make
<<<<<<< HEAD
          command: npm install && cd musician &&
=======
          command: npm install && npm run test
>>>>>>> 2a023e0ce5e39182dcf09621d2e517c99cfb9fd9
      - coveralls/upload