version: 2.1

orbs: 
  coveralls: coveralls/coveralls@1.0.6

jobs:
  say-hello:

    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout
      - run: ls; pwd;


workflows:
  say-hello-workflow:
    jobs:
      - say-hello