version: 2.1

orbs: 
  codecov: codecov/codecov@3.2.2

jobs:     

  install-and-test:
    build:
    docker:
      - image: cimg/node:16.13.2
    
    steps: 
      - checkout

      # - run:
      #     name: "Install codecov"
      #     command: "curl -Os https://uploader.codecov.io/latest/linux/codecov chmod +x codecov ./codecov"
      - run: 
          name: "List files"
          command: "ls;"

      - run: 
          name: "Install npm modules in musician"
          command: "cd musician; npm install; npm install jest; npm install --save jest-coverage-badges; sudo npm install -g codecov;"

      - run:
          name: "Install npm modules in outer folder"
          command: "npm run setup"
        
      - run: 
          name: "Initialize the coveage file location"
          command: "npm run initialize-coverage"

      - run: "cd musician; npm test" || true
      
      - run:
          name: "Generate badges from coverage-summary.json"
          command: "npm run badges"


workflows:
  Install-and-test:
    jobs:
      - install-and-test