version: 2.1

orbs: 
  coveralls: coveralls/coveralls@1.0.6
  repo_token: uBUJ6eadGjnX1wRxPovjb7PqxLicixf5B

workflows:
  test-deploy:
    jobs:
      - test
      
jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: node --version
