version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6  
  node: circleci/node@5.0.2
  
jobs:
  build:
    docker:
      - image: 'circleci/node:16.13.2'
    steps:
      - checkout
      - run:
          name: Install and Make
          command: npm install && npx jest --coverage
      - coveralls/upload